name: Zgłoś błąd!
description: Znalazłeś błąd? Prześlij go tu abyśmy mogli go jak najszybciej rozwiązać!
labels: ["BŁĄD"]
body:
  - type: checkboxes
    id: searched
    attributes:
      label: Zasady
      options:
        - label: "Używam najnowszej wersji pluginu radziuXRay"
          required: true
  - type: input
    id: discord_tag
    attributes:
      label: Twój discord tag (opcjonalne)
      description: Jak możemy się z Tobą skontaktować w celu uzyskania więcej informacji?
      placeholder: np. DiscordTag#0001
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Co się stało?
      description: Krótki opis co się stało podczas używania naszego pluginu.
      placeholder: Powiedz nam co widzisz!
      placeholder: "np. Po włączeniu opcji ... plugin wyrzuca błąd w konsoli"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Co trzeba zrobić aby wygenerować ten sam błąd
      description: Opisz nam, jak możemy uzyskać ten sam błąd?
      placeholder: |
        1. Wejdź w '...'
        2. Kliknij w '....'
        3. Zjedź w dół na '....'
        4. Zobacz błąd
    validations:
      required: true
  - type: dropdown
    id: server_version
    attributes:
      label: Wersja serwera
      description: "Wybierz swoją wersje serwera na którym grasz"
      options:
        - 1.17.2
        - 1.18
        - 1.18.1
        - 1.18.2
        - 1.19
  - type: dropdown
    id: server_name
    attributes:
      label: Serwer
      description: "Wybierz na którym z tych serwerów wystepuje błąd."
      options:
        - wither-craft.pl
        - privatebeta.wither-craft.pl
        - inny wspierany serwer
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshoty / Filmy
      description: Wklej screenshot aby pomóc nam w rozwiązaniu Twojego problemu.
  - type: markdown
    attributes:
      value: |
        ## Dziękujemy za wypełnienie formularza błędu.
