name: Zgłaszanie błędu | radziuDev
description: Zgłoś nam twój błąd dotyczący pluginu radziuXRay
labels: ["BŁĄD"]
body:
  - type: checkboxes
    id: searched
    attributes:
      label: Zasady
      options:
        - label: "Używam najnowszej wersji pluginu radziuXRay"
          required: true
  - type: input
    id: discord_tag
    attributes:
      label: Twój discord tag (opcjonalne)
      description: Jak możemy się z Tobą skontaktować w celu uzyskania więcej informacji?
      placeholder: np. DiscordTag#0001
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Co się stało?
      description: Krótki opis co się stało podczas używania naszego pluginu.
      placeholder: Powiedz nam co widzisz!
      placeholder: "np. Po włączeniu opcji ... plugin wyrzuca błąd w konsoli"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Co trzeba zrobić aby wygenerować ten sam błąd
      description: Opisz nam, jak możemy uzyskać ten sam błąd?
      placeholder: |
        1. Wejdź w '...'
        2. Kliknij w '....'
        3. Zjedź w dół na '....'
        4. Zobacz błąd
    validations:
      required: true
  - type: textarea
    id: server_version
    attributes:
      label: Wersja serwer
      description: "(użyj komendy `/version` i wpisz tutaj)"
      placeholder: |
        Użyj komendy `/version` i wklej wynik tutaj.
        
        Przykład:
        This server is running Paper version git-Paper-788 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)"
  - type: textarea
    id: full_server_log
    attributes:
      label: FULL server log
      placeholder: "You can drag and drop your full server log here"      
  - type: textarea
    id: logs
    attributes:
      label: Błąd (opcjonalne)
      description: Wklej tutaj błąd.
      render: shell
      placeholder: |
        [19:26:04] [Craft Scheduler Thread - 18 - ItemsAdder/WARN]: [ItemsAdder] Plugin ItemsAdder v2.4.16 generated an exception while executing task 22801
          java.lang.ExceptionInInitializerError: null
            at dev.lone.itemsadder.l.j.a(SourceFile:166) ~[ItemsAdder.jar:?]
            at dev.lone.itemsadder.l.j.av(SourceFile:104) ~[ItemsAdder.jar:?]
            at dev.lone.itemsadder.l.a.a(SourceFile:164) ~[ItemsAdder.jar:?]
            at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Airplane-84]
            at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [patched_1.17.1.jar:git-Airplane-84]
            at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.17.1.jar:git-Airplane-84]
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
            at java.lang.Thread.run(Thread.java:831) [?:?]
          Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.util.zip.ZipEntry.size accessible: module java.base does not "opens java.util.zip" to unnamed module @6f6969ca
            at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
            at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
            at java.lang.reflect.Field.checkCanSetAccessible(Field.java:177) ~[?:?]
            at java.lang.reflect.Field.setAccessible(Field.java:171) ~[?:?]
            at com.comphenix.protocol.reflect.FieldUtils.getField(FieldUtils.java:111) ~[PROTOCOLLIB.jar:?]
            at dev.lone.itemsadder.l.k.<clinit>(SourceFile:12) ~[ItemsAdder.jar:?]
            ... 9 more
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshoty / Filmy
      description: Wklej screenshot aby pomóc nam w rozwiązaniu Twojego problemu.
  - type: markdown
    attributes:
      value: |
        ## Dziękujemy za wypełnienie formularza błędu.
