name: Zgłaszanie błędu | radziuDev
description: Zgłoś nam twój błąd dotyczący pluginu radziuXRay
labels: ["BŁĄD"]
body:
  - type: checkboxes
    id: searched
    attributes:
      label: Zasady
      options:
        - label: "Używam najnowszej wersji pluginu radziuXRay"
          required: true
  - type: input
    id: discord_tag
    attributes:
      label: Twój discord tag (opcjonalne)
      description: Jak możemy się z Tobą skontaktować w celu uzyskania więcej informacji?
      placeholder: np. DiscordTag#0001
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Co się stało?
      description: Krótki opis co się stało podczas używania naszego pluginu.
      placeholder: Powiedz nam co widzisz!
      placeholder: "np. Po włączeniu opcji ... plugin wyrzuca błąd w konsoli"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Co trzeba zrobić aby wygenerować ten sam błąd
      description: Opisz nam, jak możemy uzyskać ten sam błąd?
      placeholder: |
        1. Wejdź w '...'
        2. Kliknij w '....'
        3. Zjedź w dół na '....'
        4. Zobacz błąd
    validations:
      required: true
  - type: textarea
    id: server_version
    attributes:
      label: Wersja serwer
      description: "(użyj komendy `/version` i wpisz tutaj)"
      placeholder: |
        Użyj komendy `/version` i wklej wynik tutaj.
        
        Przykład:
        This server is running Paper version git-Paper-788 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)"
  - type: textarea
    id: full_server_log
    attributes:
      label: PEŁNE logi serwera
      placeholder: "Prześlij nam logi serwera - to może nam pomóc w naprawie błędu."      
  - type: textarea
    id: logs
    attributes:
      label: Błąd (opcjonalne)
      description: Wklej tutaj błąd.
      render: shell
      placeholder: |
        [19:01:04] [Server thread/ERROR]: Could not load 'plugins\radziuLifeSteal2.jar' in folder 'plugins'
          org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.19
            at org.bukkit.craftbukkit.v1_18_R2.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:375) ~[purpur-1.18.2.jar:git-Purpur-1614]
            at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
            at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
            at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
            at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[purpur-1.18.2.jar:git-Purpur-1614]
            at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[purpur-1.18.2.jar:git-Purpur-1614]
            at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1614]
            at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1614]
            at java.lang.Thread.run(Thread.java:833) ~[?:?]
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshoty / Filmy
      description: Wklej screenshot aby pomóc nam w rozwiązaniu Twojego problemu.
  - type: markdown
    attributes:
      value: |
        ## Dziękujemy za wypełnienie formularza błędu.
