name: Nowa funkcja
description: Sugestie dotyczące nowych funkcji w pluginie
labels: ["Sugestia"]
body:
  - type: checkboxes
    id: searched
    attributes:
      label: Zasady
      options:
        - label: "Używam najnowszej wersji pluginu radziuXRay"
          required: true
  - type: input
    id: discord_tag
    attributes:
      label: Twój discord tag (opcjonalne)
      description: Jak możemy się z Tobą skontaktować w celu uzyskania więcej informacji?
      placeholder: np. DiscordTag#0001
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: "Opisz nam swoją sugestie"
      placeholder: "Chce auto kopanie bo fajne"
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Czy twoja sugestia jest również związana z problemem?
      placeholder: "Przykład: Denerwuje mnie to że gdy [...] to dzieje się to [...]"
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: "Dodatkowe informacje"
      placeholder: "Jeśli chcesz coś dodać - napisz to tutaj."
  - type: markdown
    attributes:
      value: |
        ## Dziękujemy za sugestię!
